django_echart/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('echart/',include('echart.urls')),
]

echart/urls.py

from django.urls import path
from . import views
from .bar import barview

app_name='echart'
urlpatterns=[
    path('',views.index,name='index'),
    path('first',views.echartFirst,name='first'),
    path('echartupdate',views.echartUpdate,name='echartupdate'),
    path('echartdataset',views.echartDataset,name='echartdataset'),
    path('barsimple',barview.barSimple,name='barsimple'),
    path('barsimpledata',barview.barSimpleData,name='barsimpledata'),
    path('echartmedia',views.echartMedia,name='echartmedia'),
    path('echartvisualmap',views.echartVisualMap,name='echartvisualmap'),
    path('echartevent',views.echartEvent,name='echartevent'),
    path('echartgl',views.echartGL,name='echartgl'),
    path('echartcustom',views.echartCustom,name='echartcustom'),
]

echart/models.py
from django.db import models

# Create your models here.

echart/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse

# Create your views here.


def index(request):
    return HttpResponse("this is echart index")


def echartFirst(request):
    return render(request,'echart/first.html')

# echarts数据更新实例
def echartUpdate(request):
    return render(request, 'echart/echart_update_data.html')

def echartDataset(request):
    return render(request,'echart/echart_dataset.html')

def echartMedia(request):
    return render(request,'echart/echart_media.html')

def echartVisualMap(request):
    return render(request,'echart/echart_visualMap.html')

def echartEvent(request):
    return render(request,'echart/echart_event.html')

def echartGL(request):
    return render(request,'echart/echart_GL.html')

def echartCustom(request):
    return render(request,'echart/echart_custom.html')

echart/templates/common/echart_base.html

{% load staticfiles %}
{% block echart_base %}
    <link rel="shortcut icon" href="{%static "favicon.png" %}" />
    <script type="text/javascript" src="{% static 'jquery-1.9.1.js' %}"></script>
    <script type="text/javascript" src="{% static 'echart/echarts.js' %}"></script>
{% endblock %}

echart/templates/echart/echart_GL.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>EchartGL实例</title>
    {% include 'common/echart_base.html' %}
    <script type="text/javascript" src="{% static 'echart/echarts-gl.js' %}"></script>

    
    <script type="text/javascript">
        $(document).ready(function () {

            /**************************************高斯分布************************************************/
            function makeGaussian(amplitude, x0, y0, sigmaX, sigmaY) {
                return function (amplitude, x0, y0, sigmaX, sigmaY, x, y) {
                    var exponent = -(
                            ( Math.pow(x - x0, 2) / (2 * Math.pow(sigmaX, 2)))
                            + ( Math.pow(y - y0, 2) / (2 * Math.pow(sigmaY, 2)))
                        );
                    return amplitude * Math.pow(Math.E, exponent);
                }.bind(null, amplitude, x0, y0, sigmaX, sigmaY);
            }
            // 创建一个高斯分布函数
            var gaussian = makeGaussian(50, 0, 0, 20, 20);

            var data = [];
            for (var i = 0; i < 1000; i++) {
                // x, y 随机分布
                var x = Math.random() * 100 - 50;
                var y = Math.random() * 100 - 50;
                var z = gaussian(x, y);
                data.push([x, y, z]);
            }


            var option={
                legend:{icon: 'roundRect'},
                color:'#0b9eff',
                backgroundColor:'rgba(50,59,100,0.3)',
                tooltip:{},
                grid3D:{},
                xAxis3D:{},
                yAxis3D:{},
                zAxis3D:{max:100},
                series:[{
                    name:'高斯分布',
                    //三维散点图
                    type:'scatter3D',
                    data:data
                    }
                ]
            };

            /**************************************三维曲面图 surface************************************************/
            var data = [];
            // 曲面图要求给入的数据是网格形式按顺序分布。
            for (var y = -50; y <= 50; y++) {
                for (var x = -50; x <= 50; x++) {
                    var z = gaussian(x, y);
                    data.push([x, y, z]);
                }
            }
            option1 = {
                legend:{},
                backgroundColor:'rgba(116,50,92,0.7)',
                color:'#6f84ff',
                grid3D: {},
                xAxis3D: {},
                yAxis3D: {},
                zAxis3D: { max: 60 },
                series: [{
                    name:'surface图',
                    type: 'surface',
                    data: data
                }]
            }

            /**************************************自定义映射三维图************************************************/
            var lifedata=[];

            $.ajax({
                url:"{% static 'life-expectancy-table.json' %}",
                method:'POST',
                async:false,
                success:function (data) {
                    lifedata=data;
                }
            });

            option2={
                legend:{icon: 'roundRect'},
                tooltip:{},
                backgroundColor:'rgba(159,168,163,0.3)',
                color:'#ff7714',
                grid3D: {
                    viewControl: {
                        // 使用正交投影。
                        projection: 'orthographic'
                    }
                },
                //申明x,y轴为类目轴
                xAxis3D: {type:'category'},
                //yAxis3D: {type:'category'},
                yAxis3D: {type:'log'},
                zAxis3D:{},
                visualMap: {
                    calculable: true,
                    max: 100,
                    // 维度的名字默认就是表头的属性名
                    dimension: 'Life Expectancy',
                    inRange: {
                        color: ['#313695', '#4575b4', '#74add1', '#abd9e9', '#e0f3f8', '#ffffbf', '#fee090', '#fdae61', '#f46d43', '#d73027', '#a50026']
                    }
                },
                dataset:{
                    dimension:["Income","Life Expectancy","Population","Country","Year"],
                    source:lifedata
                },
                series:[
                    {
                        name:'人员消费',
                        type:'bar3D',
                        symbolSize:5,
                        //自定义x,y,z轴的映射
                        encode:{
                            x:"Country",
                            y:"Year",
                            z:"Income",
                            //tooltip: [0, 1, 2, 3, 4]
                        }
                        //默认前三列映射到x,y,z
                        //data:lifedata
                    }
                ]
            }

            myChart=echarts.init(document.getElementById('echart_gl'));
            myChart.setOption(option1);

        })
    </script>
</head>
<body>
<div id="echart_gl" style="width: 900px;height: 700px;margin: 0 auto;border:1px solid lightgrey;"></div>
</body>
</html>

echart/templates/echart/echart_bar/bar_simple.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">

    <title>barsimple</title>
    <script type="text/javascript" src="{% static 'jquery-1.9.1.js' %}"/>
    <script></script>
    <script type="text/javascript" src="{% static 'echart/echarts.js' %}"/>
    <script></script>
    <script type="text/javascript">

        $(document).ready(function () {

            var bardata;
            $.ajax({
                    url:"{% url 'echart:barsimpledata' %}",
                    type:"GET",
                    dataType:"json",
                    success:function (data) {
                        console.log(data);
                        //debugger;
                        bardata = data;
                    },
                //模式是否为异步
                    async:false
            });
            //echarts 的显示设置
            option = {
                dataZoom: [
                    {   // 这个dataZoom组件，默认控制x轴。
                        type: 'slider', // 这个 dataZoom 组件是 slider 型 dataZoom 组件,滑动滑块
                        xAxisIndex: 0,
                        start: 0,      // 左边在 0% 的位置。
                        end: 100         // 右边在 100% 的位置。
                    },
                    {   // 这个dataZoom组件，也控制x轴。
                        type: 'inside', // 这个 dataZoom 组件是 inside 型 dataZoom 组件，滚动鼠标滚轮
                        xAxisIndex: 0,
                        start: 0,      // 左边在 0% 的位置。
                        end: 100         // 右边在 100% 的位置。
                    },
                    {
                        type: 'slider',
                        yAxisIndex: 0,
                        start: 0,
                        end: 100
                    },
                    {   // 这个dataZoom组件，也控制x轴。
                        type: 'inside', // 这个 dataZoom 组件是 inside 型 dataZoom 组件，滚动鼠标滚轮
                        yAxisIndex: 0,
                        start: 0,      // 左边在 0% 的位置。
                        end: 100         // 右边在 100% 的位置。
                    }
                ],
                visualMap: {
                    // 不显示 visualMap 组件，只用于明暗度的映射
                    show: true,
                    // 映射的最小值为 80
                    min: 10,
                    // 映射的最大值为 600
                    max: 500,
                    inRange: {
                        // 明暗度的范围是 0 到 1
                        colorLightness: [0.3, 0.7],
                        symbolSize: [30, 100]
                    }
                },
                backgroundColor: 'rgba(200,200,200,0.5)',
                textStyle: {
                    color: 'rgba(0, 255, 100, 0.7)',
                },
                title:{
                    show:true,
                    text:"{a|条形图实例}",
                    /*  text: 'subtextStyle.rich使用', */
                    subtext: '{a|名称：}{b|销量}',
                    left: 'left',
                    //backgroundColor:'rgba(255,255,255,0.3)',

                    textStyle: {
                        //富文本样式
                         rich: {
                             a: { //开头和结尾的文字样式
                                 color: 'rgba(100,100,200,0.5)',
                                 fontSize: 20,
                                 fontFamily:'微软雅黑',
                                 fontWeight:'bold',
                             }
                         }
                     },
                    subtextStyle: {
                         rich: {
                             a: { //开头和结尾的文字样式
                                 color: 'green',
                                 fontSize: 16
                             },
                             b: {
                                /*  backgroundColor: 'pink', */ //无法设置渐变色
                                 color: 'green',
                                 padding: [3, 8],
                                 fontSize: 14,
                                 fontWeight: 600,
                               /*   borderColor: '#0b4d9d',
                                 borderWidth: 1, */
                             }
                         }
                    }
                },
                legend: {
                    itemWidth:30,
                    formatter: '图例-{name}',
                    textStyle:{
                        fontSize:20,
                        color:'rgba(255,100,100,0.8)'
                    },
                    //data:bardata.legend,
                    data: [{
                        name: '销量',
                        // 强制设置图形为圆。
                        icon: 'circle',
                        // 设置文本为红色
                        textStyle: {
                            color: 'red'
                        }
                    }
                    /*
                    {
                        name: '示例',
                        // 强制设置图形为圆。
                        icon: 'circle',
                    }*/],
                    tooltip: {
                        show: true
                    }
                },
                tooltip: {},
                toolbox: {
                    show: true,
                    //设置了feature内容toolbox才会显示
                    feature: {
                        dataZoom: {
                            yAxisIndex: 'none'
                        },
                        dataView: {readOnly: false},
                        magicType: {type: ['line', 'bar']},
                        restore: {},
                        //图片下载名称
                        saveAsImage: {name:'销量'},
                    }
                },
                grid:{
                    show:true,
                    backgroundColor: 'rgba(10,10,100,0.5)',
                    shadowColor: 'rgba(0, 0, 0, 0.5)',
                    shadowBlur: 5,
                    shadowOffsetX:10,
                    shadowOffsetY:10,
                    tooltip:{
                        //trigger:'axis'
                        trigger:'item'
                    }
                },
                xAxis: {
                    type: 'category',
                    data: bardata.dataAxis,
                    inverse:false,
                    axisLabel:{
                        inside:false,
                        //X周的坐标标签旋转90度（竖直显示）
                        fontFamily:'微软雅黑',
                        color:'#ff8015',
                        fontSize:16,
                        rotate:45
                    },
                    axisPointer:{
                        show:true,
                        //type:'shadow',
                        type:'line'
                    }
                },
                yAxis: {
                    type: 'value',
                    splitLine: {
                        lineStyle: {
                            // 使用深浅的间隔色
                            color: ['#aaa', '#ddd']
                        }
                    }
                },
                // 全局调色盘。
                //color: ['#c23531','#2f4554', '#61a0a8', '#d48265', '#91c7ae','#749f83',  '#ca8622', '#bda29a','#6e7074', '#546570', '#c4ccd3'],
                series: [{
                    name: '销量',
                    type: 'bar',
                    //type: 'line',
                    //type:'scatter',
                    //color: ['#c23531','#2f4554', '#61a0a8', '#d48265', '#91c7ae','#749f83',  '#ca8622', '#bda29a','#6e7074', '#546570', '#c4ccd3'],
                    data: bardata.data
                }]
            };

            var mychart=echarts.init(document.getElementById('simple_bar'),'light');
            console.log('echarts版本：'+echarts.version);
            mychart.showLoading('default',{
                text: 'loading......',
                color: '#c23531',
                textColor: '#000',
                maskColor: 'rgba(255, 255, 255, 0.8)',
                zlevel: 0
            });
            console.log('loding......');

            console.log(option);
            //异步任务
            setTimeout(()=>{
                mychart.hideLoading();
                mychart.setOption(option);
            },1000);

            mychart.on('click',function (params) {
                alert(params.name)
            })


        });
    </script>

</head>
<body>
<div id="simple_bar" style="width: 600px;height:400px;border: 1px solid lightgrey;"></div>

</body>

</html>

echart/templates/echart/echart_custom.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    {% include 'common/echart_base.html' %}
    <title>Echart_Custom实例</title>
    <script type="text/javascript">
        $(document).ready(function () {
            /*
            var data = [[10, 16, 3, 'A'], [16, 18, 15, 'B'], [18, 26, 12, 'C'], [26, 32, 22, 'D'], [32, 56, 7, 'E'], [56, 62, 17, 'F']];
            var colorList = ['#4f81bd', '#c0504d', '#9bbb59', '#604a7b', '#948a54', '#e46c0b'];

            data = echarts.util.map(data, function (item, index) {
                return {
                    value: item,
                    itemStyle: {
                        normal: {
                            color: colorList[index]
                        }
                    }
                };
            });
            */
            var data=[{
                "value": [10, 16, 3, "A"],
                "itemStyle": {
                    "normal": {
                        "color": "#4f81bd"
                    }
                }
            }, {
                "value": [16, 18, 15, "B"],
                "itemStyle": {
                    "normal": {
                        "color": "#c0504d"
                    }
                }
            }, {
                "value": [18, 26, 12, "C"],
                "itemStyle": {
                    "normal": {
                        "color": "#9bbb59"
                    }
                }
            }, {
                "value": [26, 32, 22, "D"],
                "itemStyle": {
                    "normal": {
                        "color": "#604a7b"
                    }
                }
            }, {
                "value": [32, 56, 7, "E"],
                "itemStyle": {
                    "normal": {
                        "color": "#948a54"
                    }
                }
            }, {
                "value": [56, 62, 17, "F"],
                "itemStyle": {
                    "normal": {
                        "color": "#e46c0b"
                    }
                }
            }];

            function renderItem(params, api) {
                var yValue = api.value(2);
                var start = api.coord([api.value(0), yValue]);
                var size = api.size([api.value(1) - api.value(0), yValue]);
                var style = api.style();

                return {
                    type: 'rect',
                    shape: {
                        x: start[0],
                        y: start[1],
                        width: size[0],
                        height: size[1]
                    },
                    style: style
                };
            }

            console.log(JSON.stringify(data));

            option = {
                title: {
                    text: 'Profit',
                    left: 'center'
                },
                tooltip: {
                },
                xAxis: {
                    scale: true
                },
                yAxis: {
                },
                series: [{
                    type: 'custom',
                    renderItem: renderItem,
                    label: {
                        normal: {
                            show: true,
                            position: 'top'
                        }
                    },
                    dimensions: ['from', 'to', 'profit'],
                    encode: {
                        x: [0, 1],
                        y: 2,
                        tooltip: [0, 1, 2],
                        itemName: 3
                    },
                    data: data
                }]
            };

            myChart=echarts.init(document.getElementById('echart_custom'));
            myChart.setOption(option);
            
        })
    </script>

</head>
<body>

<div id="echart_custom" style="width: 700px;height: 600px; margin: 0 auto;background-color: rgba(116,50,92,0.7);"></div>
</body>
</html>

echart/templates/echart/echart_dataset.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>echart_dataset实例</title>
    {% include 'common/echart_base.html' %}
    <script type="text/javascript">
        $(document).ready(function () {
            option = {
                legend: {},
                tooltip: {},
                toolbox:{
                    show:true,
                    feature:{
                        dataView: {readOnly: false},
                        magicType: {type: ['line', 'bar']},
                        restore: {},
                        //图片下载名称
                        saveAsImage: {name:'dataset实例'},
                    }
                },
                backgroundColor:'rgba(0,100,150,0.5)',
                title:{
                    text:'dataset实例',
                    textStyle:{
                        color: 'rgba(200,0,200,0.5)',
                        fontSize: 20,
                        fontFamily:'微软雅黑',
                        fontWeight:'bold',
                    }
                },
                dataset: {
                    // 提供一份数据。
                    source: [
                        ['product', '2015', '2016', '2017'],
                        ['Matcha Latte', 43.3, 85.8, 93.7],
                        ['Milk Tea', 83.1, 73.4, 55.1],
                        ['Cheese Cocoa', 86.4, 65.2, 82.5],
                        ['Walnut Brownie', 72.4, 53.9, 39.1]
                    ]
                },
                // 声明一个 X 轴，类目轴（category）。默认情况下，类目轴对应到 dataset 第一列。
                xAxis: {type: 'category'},
                // 声明一个 Y 轴，数值轴。
                yAxis: {},
                // 声明多个 bar 系列，默认情况下，每个系列会自动对应到 dataset 的每一列。
                series: [
                    {type: 'bar'},
                    {type: 'bar'},
                    {type: 'bar'}
                ]
            };

            option0 = {
                dataset: {
                    // 这里指定了维度名的顺序，从而可以利用默认的维度到坐标轴的映射。
                    // 如果不指定 dimensions，也可以通过指定 series.encode 完成映射，参见后文。
                    dimensions: ['product', '2015', '2016', '2017'],
                    source: [
                        {product: 'Matcha Latte', '2015': 10.3, '2016': 85.8, '2017': 93.7},
                        {product: 'Milk Tea', '2015': 30.1, '2016': 73.4, '2017': 55.1},
                        {product: 'Cheese Cocoa', '2015': 50.4, '2016': 65.2, '2017': 82.5},
                        {product: 'Walnut Brownie', '2015': 80.4, '2016': 53.9, '2017': 39.1}
                    ]
                },
            };

            //dataset数据自定义映射
            option1 = {
                legend: {
                    //type:'scroll',
                    //width:'80%',
                    //left:0,
                    top:'7%'
                },
                tooltip: {},
                backgroundColor:'rgba(255,0,100,0.6)',
                toolbox:{
                    show:true,
                    left:'center',
                    feature: {
                        dataView: {readOnly: false},
                        magicType: {type: ['line', 'bar']},
                        saveAsImage: {name:'dataset实例'}
                    }
                },
                dataset: {
                    source: [
                        ['product', '2012', '2013', '2014', '2015'],
                        ['Matcha Latte', 41.1, 30.4, 65.1, 53.3],
                        ['Milk Tea', 86.5, 92.1, 85.7, 83.1],
                        ['Cheese Cocoa', 24.1, 67.2, 79.5, 86.4]
                    ]
                },
                xAxis: [
                    {type: 'category', gridIndex: 0},
                    {type: 'category', gridIndex: 1}
                ],
                yAxis: [
                    {gridIndex: 0},
                    {gridIndex: 1}
                ],
                //定义grid（绘图窗格）
                grid: [
                    {bottom: '55%'},
                    {top: '55%'}
                ],
                series: [
                    // 这几个系列会在第一个直角坐标系中，每个系列对应到 dataset 的每一行。
                    {type: 'bar', seriesLayoutBy: 'row'},
                    {type: 'bar', seriesLayoutBy: 'row'},
                    {type: 'bar', seriesLayoutBy: 'row'},
                    // 这几个系列会在第二个直角坐标系中，每个系列对应到 dataset 的每一列。
                    {type: 'bar', xAxisIndex: 1, yAxisIndex: 1},
                    {type: 'bar', xAxisIndex: 1, yAxisIndex: 1},
                    {type: 'bar', xAxisIndex: 1, yAxisIndex: 1},
                    {type: 'bar', xAxisIndex: 1, yAxisIndex: 1}
                ]
            };
            /*
            当我们把系列（series）对应到“列”的时候，那么每一列就称为一个“维度（dimension）”，而每一行称为数据项（item）。
            反之，如果我们把系列（series）对应到表行，那么每一行就是“维度（dimension）”，每一列就是数据项（item）。
            */

            //使用encode时需要手动设置每个series的name和legend，tooltip
            var option2 = {
                legend:{itemWidth:30,icon:'roundRect',orient:'vertical'},
                //开启tooltip显示
                tooltip:{width:30,textStyle:{color:'yellow'}},
                backgroundColor:'#eedeb0',
                dataset: {
                    dimensions:['score', 'amount', 'product','price'],
                    source: [
                        {product: 'Matcha Latte', count: 823, score: 95.8,price:50},
                        {product: 'Milk Tea', count: 235, score: 81.4,price:56},
                        {product: 'Cheese Cocoa', count: 1042, score: 91.2,price:45},
                        {product: 'Walnut Brownie', count: 988, score: 76.9,price:60}
                    ]
                },
                xAxis: {name:['score','price']},
                yAxis: {type: 'category',name:'product'},
                grid:{
                    left: '15%',
                },
                series: [
                    {
                        name:'price',
                        type: 'bar',
                        encode: {
                            // 将 "amount" 列映射到 X 轴。
                            tooltip:['price'],
                            //seriesName: [0, 1],
                            x: ['price'],
                            // 将 "product" 列映射到 Y 轴。
                            y: 'product'
                        }
                    },
                    {
                        name:'score',
                        type: 'bar',
                        encode: {
                            // 将 "amount" 列映射到 X 轴。
                            tooltip:['score'],
                            //seriesName: [0, 1],
                            x: ['score'],
                            // 将 "product" 列映射到 Y 轴。
                            y: 'product'
                        }
                    }
                ]
            };

            echartinstance=echarts.init(document.getElementById('echart_dataset'),'light');
            echartinstance.setOption(option);

            setTimeout(function (e) {
                console.log('开始变换');
                echartinstance.setOption(option0);
            },2000);

            echartinstance1=echarts.init(document.getElementById('echart_dataset1'));
            echartinstance1.setOption(option1);
            echartinstance1=echarts.init(document.getElementById('echart_dataset2'));
            echartinstance1.setOption(option2);

        })
    </script>
</head>
<body>
<center>
    <div >
        <div id="echart_dataset" style="width:700px;height: 400px;display: inline-block;"></div>
        <div id="echart_dataset1" style="width:700px;height: 400px;display: inline-block;"></div>
        <div id="echart_dataset2" style="width:700px;height: 400px;display: inline-block;"></div>
    </div>
</center>
</body>
</html>

echart/templates/echart/echart_event.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    {% include 'common/echart_base.html' %}

    <title>Echart的事件和行为</title>
</head>
<body>

<div id="echart_event" style="margin:0 auto;width: 600px;height: 400px;border: 1px solid ghostwhite;"></div>

    <script type="text/javascript">
        // 基于准备好的dom，初始化echarts实例
        //内置主题样式：默认，‘light’，‘dark’
        var myChart = echarts.init(document.getElementById('echart_event'),'dark');

        itemStyle={
            normal: {
                color: 'rgb(0,100,200)',
                // 阴影的大小
                shadowBlur: 10,
                // 阴影水平方向上的偏移
                shadowOffsetX: 5,
                // 阴影垂直方向上的偏移
                shadowOffsetY: 5,
                // 阴影颜色
                shadowColor: 'rgba(0, 200, 20, 0.7)'
            },
            //鼠标 hover 的时候
            emphasis: {
                shadowBlur: 10,
                shadowColor: 'rgba(0, 0, 0, 0.7)'
            }
        }

        // 指定图表的配置项和数据
        var option = {
            title: {
                text: 'ECharts 事件和行为'
            },
            tooltip: {},
            toolbox:{
                show:true,
                feature:{
                    dataView: {readOnly: false},
                    magicType: {type: ['line', 'bar']},
                    restore: {},
                    //图片下载名称
                    saveAsImage: {name:'示例'},
                }
            },
            legend: {
                data:['销量']
            },
            xAxis: {
                axisLabel:{
                    color:'#ff8015',
                    fontFamily:'微软雅黑',
                    //fontWeight:'bold',
                    fontSize:15,
                    rotate:90
                },
                data: ["衬衫","羊毛衫","雪纺衫","裤子","高跟鞋","袜子"]
            },
            yAxis: {},
            series: [{
                name: '销量',
                type: 'bar',
                symbolSize:[20,20],
                data: [
                    {value:5,itemStyle:itemStyle},
                    //5,
                    20, 36, 10, 10, 20
                ]
            }]
        };

        console.log(echarts.version);
        // 使用刚指定的配置项和数据显示图表。

        myChart.setOption(option);
        
        myChart.on('click',function (params) {
            alert(
                params.seriesName+":\n"+
                params.name
            );
        });
        
        myChart.on('legendselectchanged',function (params) {
            var selected=params.selected[params.name];
            // 在控制台中打印
            alert("所有图例："+JSON.stringify(params.selected)+"\n"+(selected ? '选中了' : '取消选中了') + '图例' + params.name);
            // 打印所有图例的状态
            console.log(params.selected);
        })
        
        /*
        myChart.on('mouseover',function(params) {
            if (params.componetType=='xAxis'){
                alert('xAxis.category:'+params.seriesName+"-"+params.seriesIndex+"\n"+params.name);
            }else if (params.componentType=='series') {
                alert('series:'+params.seriesName+"-"+params.seriesIndex+"\n"+params.name);
            }
        });
        */
        
    </script>
</body>
</html>